# Generated by Django 5.1.4 on 2024-12-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80)),
                ('years', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
    ]
